# Generated by Django 3.0.7 on 2020-06-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_auto_20200622_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
