# Generated by Django 3.0.7 on 2020-06-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_remove_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trialquestions', to='trial.TrialTest'),
            preserve_default=False,
        ),
    ]
