# Generated by Django 3.0.7 on 2020-06-23 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trial', '0004_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.TrialTest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentquiz_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
