# Generated by Django 3.0.7 on 2020-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_candidatestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialtest',
            name='roll_out',
            field=models.BooleanField(default=False),
        ),
    ]
