# Generated by Django 3.0.7 on 2020-06-30 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_trialtest_roll_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialtest',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='trialtest',
            name='description',
            field=models.CharField(default='this too', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trialtest',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trialtest',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='trialtest',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
